name: Sequential workflow (1. update details, 2. run tests)

on:
  workflow_dispatch:

  schedule:
  - cron: "0 10 * * *" # attempts to run every day at 6pm SGT

jobs:
  run-update-script:
    name: Update details in TEST_EPISODE
    uses: .github/workflows/update.yml

  run-tests-pytest:
    name: Run tests using Pytest
    uses: .github/workflows/test.yml