name: Sequential (1. health, 2. update, 3. tests)

on:
  workflow_dispatch:

  schedule:
    - cron: "0 10 * * 6" # attempts to run every Saturday at 6pm SGT

jobs:
  _run-health-script:
    name: Check tver.jp is reachable
    uses: ./.github/workflows/health.yml

  _run-tests-pytest:
    name: Run tests using Pytest
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs: _run-health-script
