name: Run tests using Pytest

on:
  workflow_call:

  workflow_dispatch:

jobs:
  run-tests-pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Pytest for testing purposes
        run: pip install pytest pytest-cov

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPNGate via OpenVPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ./.github/workflows/vpngate_public-vpn-187.opengw.net_udp_1195.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: Run tests using Pytest
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: coverage run -m pytest -v -s

      - name: Generate report using Coverage
        run: coverage report -m
