name: Update details in TEST_EPISODE

on:
  workflow_dispatch:

  schedule:
    - cron: "0 10 * * *" # attempts to run every day at 6pm SGT

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

jobs:
  run-update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytz for update script
        run: pip install pytz -U

      - name: Run the update script
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python .github/workflows/update.py

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: |
          if ! git diff --cached --quiet; then
            git diff --cached
            git config user.name $GIT_USERNAME
            git config user.email $GIT_EMAIL
            git commit -m "[auto] Update details in TEST_EPISODE" -m "Triggered by: ${{ github.event_name }}, Job: $GITHUB_JOB, Run ID: $GITHUB_RUN_ID, Run Number: $GITHUB_RUN_NUMBER"
          else
            echo "No changes to commit"
          fi

      - name: Push code to tver branch
        run: git push origin tver
